### ISSUE TITLE
JWKS request [question]

### ISSUE THREAD

**Issue by alexhermida** [dorinclisu/fastapi-auth0#13]
Hi @dorinclisu thank for the library, this is great and very straightforward!

I have a question/suggestion, I can see that the request for retrieving the JSON web key sets is hardcoded during the entity initialisation (https://github.com/dorinclisu/fastapi-auth0/blob/ae5256d06e8cd9bdc17c1138178be9612b24e7dc/src/fastapi_auth0/auth.py#L85)

So, in my case, my tests suit is fully running locally with a signed token that I'm generating locally instead of making external requests to Auth0; also, for uncoupling the tests suit in case I have to move out of Auth0 in the future.

Currently I avoid the issue monkey patching the entity so it works but I think that could be easy if we can extract that specific pice of code out of the initialisation.

What do you think?

Thanks again!

**Comment by dorinclisu** [comment]
We can certainly extract the request as a separate function for calling it regularly (in case of tenant secret rotation), but I don't think we can remove it from initialization, and I don't understand why would you want to do something like that.

First of all, nothing prevents you from doing end-to-end testing, as communicating with auth0 servers is free and not limited in any significant way (except for M2M tokens).

Secondly, when testing your API there is no need to test the authentication, which is already thoroughly tested in this library. The auth can be cleanly decoupled by taking advantage of the clever fastapi dependency injection system.

See https://fastapi.tiangolo.com/advanced/testing-dependencies/
In this case, you would override auth.get_user with your custom function that injects a test user of your choice.

**Comment by alexhermida** [comment]
Thanks for the quick answer.

> when testing your API there is no need to test the authentication,
I'm migrating custom code and I already have the specific tests for authentication, I could remove them but as it is now I have visibility of the new custom errors and responses.

>See https://fastapi.tiangolo.com/advanced/testing-dependencies/
Yes I'm aware of it, I was using it. Thanks! 😄
