### ISSUE TITLE
Support for multiple audience

### ISSUE THREAD

**Issue by pranaysharmamagicmemories** [dorinclisu/fastapi-auth0#18]
`api_audience `parameter only takes a single string. How can I initiate with support for multiple audience (validates from a list of audience, so multiple clients can connect)

**Comment by dorinclisu** [comment]
API audience is the API identifier, so it doesn't make any sense to support multiple audiences. Clients are independent of the API so they can connect as long as they specify the correct audience. I think you may be confusing api audience with client identifier.

If you want to split your routes into multiple audiences you can instantiate multiple Auth0 objects each with its own api_audience and then use them correspondingly.

**Comment by pranaysharmamagicmemories** [comment]
Thank you, can you please provide an example of how to bind multiple Auth0 objects on same api endpoint?

**Comment by dorinclisu** [comment]
https://github.com/dorinclisu/fastapi-auth0/blob/ae5256d06e8cd9bdc17c1138178be9612b24e7dc/tests/test_auth.py
Look for `auth`, `auth_custom` and `auth_guest`.
