### ISSUE TITLE
Change of license to Apache v2?

### ISSUE THREAD

**Issue by junoriosity** [dorinclisu/fastapi-auth0#25]
Hi @dorinclisu ,

I really like your work here and I would like to incorporate it into my solution, which is currently open-sourced under the Apache v2 license. 

Since this would not be possible, if I use a package with GPL version 3 license, I was wondering whether you are open to change the license to Apache v2? Or do you have some specific objections to that?

**Comment by dorinclisu** [comment]
Would changing to MIT license work for you?

**Comment by junoriosity** [comment]
@dorinclisu Oh yes, that would be awesome. :)

**Comment by dorinclisu** [comment]
Done
