### ISSUE TITLE
Update PyPI package after license change

### ISSUE THREAD

**Issue by robbellMF** [dorinclisu/fastapi-auth0#26]
Hi @dorinclisu ,

I really appreciate your work on this project and changing the project to MIT license. Following on from #25 , would you be able to publish an updated package to pypi?

Thanks!

**Comment by thinkGeist** [comment]
Seconding this! I would also appreciate updating the PyPI to reflect the license changes as it causes analysis tools (e.g. Snyk) to be quite noisy as they're still seeing the GPL-3.0 license.

**Comment by dorinclisu** [comment]
Published in 0.3.2.

**Comment by robbellMF** [comment]
Thanks @dorinclisu. Really appreciated.
