### ISSUE TITLE
Creating a M2M-only check.

### ISSUE THREAD

**Issue by Noxville** [dorinclisu/fastapi-auth0#27]
Is there a nifty way to create an option to only allow m2m clients to use a specific endpoint, or do you suggest just using the CustomAuth0User workflow and then checking the grant-type on each endpoint?

An extension to this question might be allowing only clients with a  custom scopes or those which are m2m tokens. 

Regards.

**Comment by dorinclisu** [comment]
Yes there is, by using custom permissions (scopes).

First of all, M2M apps are the final users, so we can assign permissions to them like this:
<img width="640" alt="Screenshot 2022-11-05 at 13 12 47" src="https://user-images.githubusercontent.com/13818396/200117290-eab2bfb2-43cf-4d70-ad69-66607cf51b20.png">

In contrast, SPA apps have no assignable permissions, but the final users who sign up via the associated connector can be assigned permissions like this:
<img width="640" alt="Screenshot 2022-11-05 at 13 21 40" src="https://user-images.githubusercontent.com/13818396/200117448-6318d22d-1f3f-438e-b669-4ef0cc45cf9e.png">

So even though the fastapi endpoint does not natively differentiate between the types of applications used to obtain the access tokens (though you could also implement the hack with CustomAuth0User), you can obtain infinite granularity control over who has access to what by:
1. Defining the set of permissions for the API and assigning them appropriately to the web users and m2m apps via auth0.
2. Restricting endpoint access by declaring the appropriate scopes via this lib (https://github.com/dorinclisu/fastapi-auth0/blob/90e93815cdcdad3578487e095f8609a60382663d/tests/test_auth.py#L67-L69)

Concretely, for your first question, to only allow m2m clients, you would create a permission `m2m_only` that you assign to the m2m app and none of the other users. Then you code `Security(auth.get_user, scopes=["m2m_only"]`

For your second question, the answer should be obvious, if by "only clients with a custom scopes" you mean users in auth0 terminology (which may or may not be the same as other auth providers, but here we have to stick with auth0 to avoid confusion).

**Comment by Noxville** [comment]
Great - thanks for the reply. 

I've noticed that in some older existing (private) codebase that there were checks if the grant-type (`gty `in the token) are `'client-credentials'` it implied client ID + secret was used to auth, which is only possible in a m2m workflow. My feeling is that despite this making some sense as a method of determining if another app (i.e. a trusted source) is making a request, it seems a bit fragile as a check.

**Comment by dorinclisu** [comment]
Yes client-credentials does imply that client ID + secret was used (so implicitly a trusted client) but this can also be the case for hybrid apps that are not m2m-only. For example, see the generic auth0 Default App:
<img width="640" alt="Screenshot 2022-11-13 at 18 38 02" src="https://user-images.githubusercontent.com/13818396/201533537-a36a08ca-9025-4d12-813c-fb505efcb0a0.png">

I'm not sure if this would be a big problem in practice but I guess it's yet another reason to not rely on this fragile assuption for API authorization purposes.

So if there are no further questions, could we close this?

**Comment by Noxville** [comment]
Yeah absolutely, thank you for the really detailed responses.
